### ISSUE TITLE
License

### ISSUE THREAD

**Issue by amytimed** [EJTH/phun-js-box2d#1]
Hey! This is a really cool project, but it doesn't have a license and it's unclear how people can use it.

I'm working on an open-source 2D physics game similar to Algodoo, and was interested in making an Algodoo scene importer for it, and I thought code from this repo might be able to help me make that, but I can't do anything without a clear license.

**Comment by EJTH** [comment]
Hello! Sorry for the VERY late reply. I somehow have missed your request because I am following so many other projects on github. Also this project is sort of abandoned, or rather on ice atm as I have so much other stuff to do, not least real boring work.

Regarding the license of this project then it is a good question. I guess I will have to figure it out.
I would have followed the license set by LiquidFun, the physics engine I used, but that project seems abandoned and it doesn't mention a license, even though its from google lol.

Regarding the parser defined in [parser.pegjs](https://github.com/EJTH/phun-js-box2d/blob/master/src/parser.pegjs) and parser.js, it is 100% free, no license just free. You can use it however you wish! Consider it public domain!

Regarding the thyme-runtime and thyme-transpiler, it is also completely free. No license, use it if you will.

**Comment by EJTH** [comment]
Also the player implementation is free. I wouldn't use any of that code though as it is a huge mess and more a quick and dirty prototype to see if I could even do it.

**Comment by EJTH** [comment]
Also, what kind of project are you doing? I have a long standing dream of making a free and open source sandbox app sort of like what phun and algodoo was. If you have such a project, then maybe we can put our heads together?

I would absolutely love to contribute to such a project!

**Comment by EJTH** [comment]
Also, note that this whole project is a huuuge mess originally from a decade ago, with node_modules included and lots of lazy broken code. I was about to get it working again in 2019, but then I got a new job and didnt have time to finish it, so it is in a very broken state atm with lots and lots of undocumented code, bugs and general "ick"

**Comment by amytimed** [comment]
Hi! Thank you very much for clarifying the license!

> I have a long standing dream of making a free and open source sandbox app sort of like what phun and algodoo was.

Same here! Since 2021, I've been working on a Box2D Algodoo remake named Simulo. Initially, I was using the Unity game engine, but I moved to pure web HTML+CSS+JS.

> If you have such a project, then maybe we can put our heads together?
> I would absolutely love to contribute to such a project!

Sure! I'm working on open-sourcing mine right now (cleaning up a few final scripts) and I have a Discord server for it if you'd like to join. We have almost 100 members in it so far: https://discord.gg/AUzmquMkB6

> Also the player implementation is free. I wouldn't use any of that code though as it is a huge mess and more a quick and dirty prototype to see if I could even do it.

I made my own player for Simulo, but I really wanted to use the Thyme transpiler to load Algodoo and Phun creations.

If you're interested, here are a few planned Simulo features:

- Multiplayer (already working)
- Sound
- JavaScript user-scripting

The project is meant to be more than just an Algodoo player, I'm trying to create a proper spiritual successor to Algodoo with more features.

> Also, note that this whole project is a huuuge mess originally from a decade ago, with node_modules included and lots of lazy broken code. I was about to get it working again in 2019, but then I got a new job and didnt have time to finish it, so it is in a very broken state atm with lots and lots of undocumented code, bugs and general "ick"

That's fine, it's still very nice and it loaded Algodoo scenes I tested with it perfectly

**Comment by amytimed** [comment]
My project uses `box2d-wasm` on the LiquidFun branch, also known as `liquidfun-wasm`. I'm using WebRTC for multiplayer with server-side physics, currently working on client-side
